# udap:meta cloud=aws region=us-east-1 target=ec2

engineer: Engineer { shape: person; udap-type: generic.user }
tf_library: Terraform Module Library { shape: rectangle; udap-type: generic.app }
pulumi_library: Pulumi Go Component Library { shape: rectangle; udap-type: generic.app }
aws_modules: AWS Modules { shape: rectangle; udap-type: aws.ec2 }
azure_modules: Azure Modules { shape: rectangle; udap-type: generic.app }
packages: Solution Packages { shape: rectangle; udap-type: generic.app }

engineer -> tf_library: git tag ref
engineer -> pulumi_library: Go import
tf_library -> aws_modules: infra/modules/aws
tf_library -> azure_modules: infra/modules/azure
pulumi_library -> aws_modules: pulumi/modules/aws
pulumi_library -> azure_modules: pulumi/modules/azure
tf_library -> packages: infra/packages
pulumi_library -> packages: pulumi/packages
packages -> aws_modules: composes
packages -> azure_modules: composes
