# udap:meta cloud=aws region=us-east-1 target=ec2

consumer: Vending Project { shape: rectangle; udap-type: generic.user }
ci: GitHub Actions { shape: rectangle; udap-type: generic.app }
state: TF State Bucket { shape: rectangle; udap-type: aws.s3 }
demo_ec2: Example EC2 { shape: rectangle; udap-type: aws.ec2 }
aws_modules: AWS Module Library { shape: rectangle; udap-type: generic.app }
azure_modules: Azure Module Library { shape: rectangle; udap-type: generic.app }

consumer -> aws_modules: source via git ref
consumer -> azure_modules: source via git ref
ci -> aws_modules: lint / validate / security scan
ci -> azure_modules: lint / validate / security scan
aws_modules -> state: remote state
aws_modules -> demo_ec2: example consumer
